dist: trusty
language: node_js
cache: npm
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2
before_install:
  - sudo apt-get install libsecret-1-dev
  - mkdir ~/.mosaic
  - chmod -R +rw ~/.mosaic
node_js:
  - "11"
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
install:
  - npm ci
script:
  - sudo npm run test:integration
  - ls -l ~/.mosaic
after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log
